version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    S3_BUCKET: myapp-dev-frontend-assets
    CLOUDFRONT_ID: E20ZFJTSX7WOZN
    REACT_APP_API_URL: http://myapp-dev-backend-alb-338517829.us-east-1.elb.amazonaws.com

phases:
  install:
    commands:
      - echo Moving to frontend folder
      - cd frontend
      - npm install

  build:
    commands:
      - echo "API URL is $REACT_APP_API_URL"
      - npm run build

  post_build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
